### ISSUE TITLE
请问我使用的是ur5机械臂和ubuntu20.04，其他配置一样，代码可以跑通吗？

### ISSUE THREAD

**Issue by xxhaonan** [dexin-wang/AFFGA_binpicking_ur5e#1]

**Comment by dexin-wang** [comment]
理论上可以跑通，遇到问题再解决

**Comment by xxhaonan** [comment]
# 我在运行scripts/policy.py时，遇到了错误
![image](https://github.com/dexin-wang/AFFGA_binpicking_ur5e/assets/81416871/3304da02-faad-49b9-a7c0-534a48496638)

`ModuleNotFoundError: No module named 'grasp_binpicking'
`
**好像代码中并没有这个模块**，希望可以解答一下！
另外，感谢您的开源code，很有帮助！

**Comment by dexin-wang** [comment]
你好，将 `detect_grasps.py` 和 `policy.py` 中的`grasp_binpicking.msg` 修改为 `AFFGA_binpicking_ur5e.msg` ，重新编译运行即可，我已经修改了源码中的该部分。
