### ISSUE TITLE
我在运行scripts/detect_grasps.py时，遇到了缺少程序的错误

### ISSUE THREAD

**Issue by xxhaonan** [dexin-wang/AFFGA_binpicking_ur5e#2]
![image](https://github.com/dexin-wang/AFFGA_binpicking_ur5e/assets/81416871/cf1cb55a-3a50-4505-a260-fbffc6a79d70)
当运行`scripts/detect_grasps.py`时，遇到
`ModuleNotFoundError: No module named 'grasp_methods.affga_net.sgdn.models.ggcnn`
我在`~/scripts/grasp_methods/affga_net/sgdn/models`中**并没有**找到`ggcnn`，望解答！
感谢您的code！

**Comment by dexin-wang** [comment]
你好，感谢你的意见，我已在代码中增加函数实现。由于实际使用的代码融合了其他抓取算法，全部安装较复杂，因此在发布的时候做了删减，只保留本论文相关的代码，可能有误删等问题，如果需要完整的测试版代码，我会上传到谷歌网盘。

https://github.com/dexin-wang/AFFGA_binpicking_ur5e/blob/9f5cd5e9846e0383e74545d0a414c1e3c3cd6e9c/scripts/grasp_methods/affga_net/sgdn/sgdn.py#L23-L41

**Comment by xxhaonan** [comment]
感谢您的耐心解答.
可是当我按照[readme](https://github.com/dexin-wang/AFFGA_binpicking_ur5e/blob/main/README.md)依次运行

1. `roslaunch AFFGA_binpicking_ur5e grasp_affga.launch`
2. `rosrun AFFGA_binpicking_ur5e policy.py`
3. `rosrun AFFGA_binpicking_ur5e detect_grasps.py`之后，终端在输出` load done`后，就没有反应了，机械臂也没有运动
![image](https://github.com/dexin-wang/AFFGA_binpicking_ur5e/assets/81416871/8e09857c-9145-4bec-9084-dd5023f034bc)
而文件`policy.py`也一直停留在输出`Waiting /grasp_start`
![image](https://github.com/dexin-wang/AFFGA_binpicking_ur5e/assets/81416871/9b0e574b-110a-4ad3-8345-7e09e6a1ce82)
于是我怀疑应该问题出在了下图中（policy.py文件）的**if判断**上
![image](https://github.com/dexin-wang/AFFGA_binpicking_ur5e/assets/81416871/984ed44a-3fd9-4d4b-9f0f-17ceb892eb51)
**是否是因为该回调函数出现了问题所导致？**
我通过`rostopic info /grasp_start`查看了该话题,得到下图
![image](https://github.com/dexin-wang/AFFGA_binpicking_ur5e/assets/81416871/bba0e7aa-65ac-4a7b-8cec-a5f7a9eec038)
想要通过`rostopic echo /grasp_start`查看话题内容,但是终端既不报错，也没有任何显示
当我尝试通过``rostopic echo /grasp_pose 
``查看`/grasp_pose`的内容时，依然遇到了同样的情况，终端既不报错，也没有任何显示
![image](https://github.com/dexin-wang/AFFGA_binpicking_ur5e/assets/81416871/7aa595d9-6bdd-475f-bcc5-08a134ebc10e)
望解答.
感谢您的code！

**Comment by dexin-wang** [comment]
你好，为了控制机械臂的抓取时机，需要用户手动向grasp_start话题发布任意消息来启动一次抓取，完成抓取后再重新发布消息

---- 回复的原邮件 ----
| 发件人 | Haonan ***@***.***> |
| 发送日期 | 2023年11月17日 17:23 |
| 收件人 | dexin-wang/AFFGA_binpicking_ur5e ***@***.***> |
| 抄送人 | Dexin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [dexin-wang/AFFGA_binpicking_ur5e] 我在运行scripts/detect_grasps.py时，遇到了缺少程序的错误 (Issue #2) |

感谢您的耐心解答.
可是当我按照readme依次运行

roslaunch AFFGA_binpicking_ur5e grasp_affga.launch
rosrun AFFGA_binpicking_ur5e policy.py
rosrun AFFGA_binpicking_ur5e detect_grasps.py之后，终端在输出 load done后，就没有反应了，机械臂也没有运动

而文件policy.py也一直停留在输出Waiting /grasp_start

于是我怀疑应该问题出在了下图中（policy.py文件）的if判断上

是否是因为该回调函数出现了问题所导致？
我通过rostopic info /grasp_start查看了该话题,得到下图

想要通过rostopic echo /grasp_start查看话题内容,但是终端既不报错，也没有任何显示
当我尝试通过rostopic echo /grasp_pose 查看/grasp_pose的内容时，依然遇到了同样的情况，终端既不报错，也没有任何显示

望解答.
感谢您的code！

**Comment by xxhaonan** [comment]
1. `roslaunch AFFGA_binpicking_ur5e grasp_affga.launch`
2. `rosrun AFFGA_binpicking_ur5e policy.py`
3. `rosrun AFFGA_binpicking_ur5e detect_grasps.py`
4. 然后每次执行抓取打开终端输入`rostopic pub /grasp_start std_msgs/Int8 '1'`
---
**是这个意思吗？**
我这样运行后,`detect_grasps.py`这个文件会直接报错
并且文件``detect_grasps.py``中好像并没有定义`self.runGraspDetection`
![image](https://github.com/dexin-wang/AFFGA_binpicking_ur5e/assets/81416871/b1c86428-d3eb-48ac-aeaf-d70aa798e2d0)

**Comment by xxhaonan** [comment]
> 你好，感谢你的意见，我已在代码中增加函数实现。由于实际使用的代码融合了其他抓取算法，全部安装较复杂，因此在发布的时候做了删减，只保留本论文相关的代码，可能有误删等问题，如果需要完整的测试版代码，我会上传到谷歌网盘。
> 
> https://github.com/dexin-wang/AFFGA_binpicking_ur5e/blob/9f5cd5e9846e0383e74545d0a414c1e3c3cd6e9c/scripts/grasp_methods/affga_net/sgdn/sgdn.py#L23-L41

可以发一下完整的代码吗？谢谢您！

**Comment by dexin-wang** [comment]
你好，最近在忙实验和项目，我会尽快回复近期的问题，感谢关注工作！

---- 回复的原邮件 ----
| 发件人 | Haonan ***@***.***> |
| 发送日期 | 2023年11月23日 10:17 |
| 收件人 | dexin-wang/AFFGA_binpicking_ur5e ***@***.***> |
| 抄送人 | Dexin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [dexin-wang/AFFGA_binpicking_ur5e] 我在运行scripts/detect_grasps.py时，遇到了缺少程序的错误 (Issue #2) |

你好，感谢你的意见，我已在代码中增加函数实现。由于实际使用的代码融合了其他抓取算法，全部安装较复杂，因此在发布的时候做了删减，只保留本论文相关的代码，可能有误删等问题，如果需要完整的测试版代码，我会上传到谷歌网盘。

https://github.com/dexin-wang/AFFGA_binpicking_ur5e/blob/9f5cd5e9846e0383e74545d0a414c1e3c3cd6e9c/scripts/grasp_methods/affga_net/sgdn/sgdn.py#L23-L41

可以发一下完整的代码吗？谢谢您！

**Comment by dexin-wang** [comment]
> > 你好，感谢你的意见，我已在代码中增加函数实现。由于实际使用的代码融合了其他抓取算法，全部安装较复杂，因此在发布的时候做了删减，只保留本论文相关的代码，可能有误删等问题，如果需要完整的测试版代码，我会上传到谷歌网盘。
> > https://github.com/dexin-wang/AFFGA_binpicking_ur5e/blob/9f5cd5e9846e0383e74545d0a414c1e3c3cd6e9c/scripts/grasp_methods/affga_net/sgdn/sgdn.py#L23-L41
> 
> 可以发一下完整的代码吗？谢谢您！

你好！项目代码已上传至google disk: https://drive.google.com/file/d/18RSFOfWELnPehyY_FrV_s8LubOmw6pUI/view?usp=drive_link
因配置复杂和删除了涉密的部分代码，建议仅作为本git项目的补充材料。
